<div class="ui-longtext ui-widget ui-widget-content ui-align-client ui-document">
    <div>
        <p>Witamy na oficjalnej stronie bilioteki ZendY.</p>
        <p>ZendY powstała jako rozwinięcie biblioteki ZendX, ułatwiającej współpracę aplikacji napisanych w Zend Framework z biblioteką jQuery. 
            ZendY wprowadza również zintegrowany model dostępu do danych oraz przyspiesza tworzenie formularzy. 
            Zależność pomiędzy ZendY, a Zend Framework przedstawia poniższy schemat:</p>

        <svg 
            version="1.1" 
            preserveAspectRatio="none" 
            xmlns="http://www.w3.org/2000/svg" 
            xmlns:xlink="http://www.w3.org/1999/xlink" 
            class="ui-svg"
            width="568px" 
            height="141px" 
            viewBox="0 0 216027 53816">

            <g transform="scale(0.63472)">
                <g id="zend" class="ui-state-hover">
                    <path class="ui-svg-element"
                          d="M 28449 8322 L 102801 8322 102801 59598 28449 59598 Z"/>
                    <g pointer-events="none" transform="matrix(381,0,0,381,32106,22911)">
                        <g transform="translate(0 23.04)">
                            <text class="ui-svg-text ui-svg-text-label" 
                                  x="60.4959092027559px" 
                                  y="0px">Zend</text>
                        </g>
                        <g transform="translate(0 29)">
                            <g transform="translate(0 23.04)">
                                <text class="ui-svg-text ui-svg-text-label" 
                                      x="27.796690452755897px" 
                                      y="0px">Framework</text>
                            </g>
                        </g>
                    </g>
                </g>

                <g id="zendx" class="ui-state-hover">
                    <path class="ui-svg-element"
                          d="M 142340 8322 L 216692 8322 216692 59598 142340 59598 Z"/>
                    <g pointer-events="none" transform="matrix(381,0,0,381,145997,28435.5)">
                        <g transform="translate(0 23.04)">
                            <text class="ui-svg-text ui-svg-text-label" 
                                  x="52.5154404527559px" 
                                  y="0px">ZendX</text>
                        </g>
                    </g>
                </g>

                <g id="zendy" class="ui-state-hover">
                    <g/>
                    <path class="ui-svg-element"
                          d="M 256491 8322 L 330843 8322 330843 59598 256491 59598 Z"/>
                    <g pointer-events="none" transform="matrix(381,0,0,381,260148,28435.5)">
                        <g transform="translate(0 23.04)">
                            <text class="ui-svg-text ui-svg-text-label" 
                                  x="52.4568467027559px" 
                                  y="0px">ZendY</text>
                        </g>
                    </g>
                </g>

                <g id="arrow1" class="ui-state-hover">
                    <path class="ui-svg-element"
                          d="M 108410 35792 L 115370 28832 115370 32312 132578 32312 132578 39272 115370 39272 115370 42752 Z"/>
                </g>

                <g id="arrow2" class="ui-state-hover">
                    <path class="ui-svg-element"
                          d="M 224234 35792 L 231194 28832 231194 32312 248402 32312 248402 39272 231194 39272 231194 42752 Z"/>
                </g>
            </g>

        </svg>

        <p>Główne części biblioteki:
            <ul>
                <li><tt>Db</tt> - pakiet zarządzania danymi, odpowiednik Zend_Db,</li>
                <li><tt>Form</tt> - pakiet formularzy, odpowiednik Zend_Form,</li>
                <li><tt>Report</tt> - pakiet raportów,</li>
                <li><tt>View</tt> - pakiet pomocników widoku, odpowiednik Zend_View</li>
            </ul></p>
        <p>Biblioteka powstała w firmie EFISH Sp. z o.o. w 2013 roku.</p>
    </div>
</div>