<div class="ui-align-center">
    <div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-front ui-dialog-buttons ui-align-center" style="width: 450px">
        <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
            <span class="ui-dialog-title">Biblioteka ZendY</span>
        </div>
        <div class="ui-dialog-content ui-widget-content">
            <div class="ui-padding-all ui-scroll-auto">
                <h3>Efish sp. z o.o.<br />
                    Printing your future
                </h3>
                <br />
                Do prawidłowego funkcjonowania aplikacji zaleca się używania przeglądarki 
                Mozilla Firefox lub Google Chrome.
                <br /><br />
                Kontakt w sprawie biblioteki i zgłaszanie błędów:<br /><br />
                <?= $this->contact['name'] ?><br />
                E-mail: <a href="mailto:<?= $this->contact['email'] ?>"><?= $this->contact['email'] ?></a><br />
            </div>
        </div>
    </div>
</div>

