<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?= $this->headMeta()->setHttpEquiv('Content-Type', 'text/html;charset=utf-8'); ?>
        <?php
        //tytuł strony
        $appTitle = $this->translate('ZendY');
        //ustawienia menu głównego
        $navigation = $this->navigation()->verticalMenu()->setIconMenu("nav");
        //bieżąca strona
        $request = Zend_Controller_Front::getInstance()->getRequest();
        $controller = $request->getControllerName();
        $action = $request->getActionName();
        $uri = '/' . $controller . '/' . $action;
        $activePage = $navigation->findByUri($uri);
        if (isset($activePage)) {
            $activePage->setActive(true);
            $activePageLabel = $activePage->getLabel();
        } else {
            $activePageLabel = '';
        }
        echo $this->headTitle($appTitle . '. ' . $this->translate($activePageLabel));
        ?>

        <?=
                $this->headLink()
                ->prependStylesheet('/application/css/common.css')
                ->prependStylesheet($this->host . '/library/jquery-ui-1.10.2/themes/base/jquery.ui.all.css')
                ->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext')
        ;
        ?>
        <?=
                $this->jQuery()
                ->setLocalPath($this->host . '/library/jquery-ui-1.10.2/jquery-1.9.1.js')
                ->setUiLocalPath($this->host . '/library/jquery-ui-1.10.2/ui/jquery-ui.js')
                ->addJavascriptFile($this->host . '/library/jquery-ui-1.10.2/globalize-master/lib/globalize.js')
                ->addJavascriptFile($this->host . '/library/jquery-ui-1.10.2/globalize-master/lib/cultures/globalize.cultures.js')
                ->addJavascriptFile($this->host . '/library/jquery-ui-1.10.2/ui/i18n/jquery-ui-i18n.js')
                ->addJavascriptFile($this->host . '/library/components/layout/layout.js')
        ;
        ?>
    </head>
    <body class="ui-layout ui-align-client">
        <?php
        if (isset($this->dialogMessages)) {
            echo $this->dialogMessages;
        }
        ?>        
        <div class="ui-align-left" style="width: 220px; background-color: #333;">
            <div class="ui-align-top" style="height: 50px;">
                <a href="/" title="Homepage" class="ui-align-center" style="
                   display: inline-block; width: 90px; height: 20px;">
                    <img style="height: 20px; padding-left: 10px;" 
                         src="/application/images/logo_small.png" />
                </a>
            </div>
            <div id="nav" class="ui-align-client" style="top: 51px;">
                <?php
                echo $this->navigation()
                        ->verticalMenu()
                        ->setActiveClass('ui-state-active')
                        ->setMinDepth(1);
                ?>
            </div>
        </div>
        <div class="ui-align-client" style="left: 220px;">
            <div class="ui-widget ui-state-active ui-align-top" 
                 style="height: 40px; border: none;">
                <h2 class="ui-align-vcenter" style="left: 1em;">
                    <?= $this->translate($activePageLabel); ?>
                </h2>
                <div class="ui-align-right ui-align-vcenter" style="width: 200px; height: 31px;">
                    <?= $this->localeForm; ?>
                </div>
            </div>
            <div class="ui-align-client" style="top: 42px">
                <?= $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>