<p>Kontenerem w formularzu podstawowym może być obiekt klasy:
<ul>
    <li><tt>ZendY\Form\Container\Panel</tt> - prosty kontener realizowany znacznikiem div,</li>
    <li><tt>ZendY\Form\Container\Box</tt> - panel pudełkowy z nagłówkiem,</li>
    <li><tt>ZendY\Form\Container\Dialog</tt> - okno dialogowe,</li>
    <li><tt>ZendY\Form\Container\Tab</tt> - panel zakładek.</li>
</ul>
Można tworzyć własne kontenery rozszerzając któryś z istniejących. 
Uproszczony diagram klas dla istniejących kontenerów wygląda następująco:<br />
[file]../application/views/scripts/zendy/form_containers.svg[/file]
</p>
<p>Kontenery formularza bazodanowego <tt>ZendY\Db\Form</tt>:
<ul>
    <li><tt>ZendY\Db\Form\Container\Navigator</tt> - nawigator rekordów (przechodzenie między rekordami), </li>
    <li><tt>ZendY\Db\Form\Container\EditDialog</tt> - okno dialogowe do edycji rekordów, </li>
    <li><tt>ZendY\Db\Form\Container\FilterDialog</tt> - okno dialogowe do filtrowania rekordów.</li>
</ul>
Uproszczony diagram klas dla kontenerów bazodanowych wygląda następująco:<br />
[file]../application/views/scripts/zendy/dbform_containers.svg[/file]
</p>