Do uruchomienia i poprawnego działania biblioteki ZendY niezbędna jest instalacja:
<ul>
<li>PHP, w wersji min. 5.4.7 - z obsługą przestrzeni nazw oraz cech</li>
<li>jQuery, w wersji min. 1.9.1 (dołączony do biblioteki)</li>
<li>jQuery UI, w wersji min. 1.10.2 (dołączony do biblioteki)</li>
<li>serwera MySQL, w wersji min. 5.5.27</li>
<li>Zend Framework 1, w wersji min. 1.12</li>
<li>ZendX</li>
</ul>